---

- name: "configuration play." 
  hosts: web
  user: ubuntu
  gather_facts: false
  vars:
    - ansible_python_interpreter: /usr/bin/python3
    - ansible_host_key_checking: false
    - ansible_stdout_callback: yaml

  pre_tasks:
    - name: "wait 300 seconds for target connection to become reachable/usable."
      wait_for_connection:
        delay: 5
        timeout: 300

    - name: "install python for Ansible."
      become: true
      raw: test -e /usr/bin/python3 || (sudo apt -y update && sudo apt install -y python3)

  roles:
    - configure-server
