---
- name: "check the environment vars."
  shell: |
    printenv
    export

- name: "sudo: check the environment vars."
  become: yes
  shell: |
    printenv
    export

- name: "update apt packages."
  become: yes
  apt:
    update_cache: yes

- name: "upgrade packages"
  become: yes
  apt:
    upgrade: yes

- name: "remove dependencies that are no longer required"
  become: yes
  apt:
    autoremove: yes

- name: "install dependencies."
  become: yes
  apt:
    name: ["nodejs", "npm"]
    state: latest
    update_cache: yes

- name: "Copy backend code to the host."
  copy:
    src: "{{ BACKEND_CODE }}"
    dest: "/var/www/html/"
