version: 2.1

### It's a good practice to keep your commands at the top of the config file. In this project, you'll need at least 2 commands:
commands:
  sayhello:
    description: "A very simple command for demonstration purposes"
    parameters:
      to:
        type: string
        default: "Hello World"
    steps:
      - run: echo << parameters.to >>

  destroy-environment:
    description: Destroy cloudformation stacks given a workflow ID.
    steps:
      - run: aws cloudformation delete-stack --stack-name "prod-${CIRCLE_WORKFLOW_ID}"

#   revert-migration:
#     description: Revert the last migration if successfully run in the current workflow.
#     ...

jobs:
  build-backend:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          name: Backend build
          command: |
            cd backend && npm i && npm run build

  build-frontend:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          name: Frontend build
          command: |
            cd frontend && npm i && npm run build

#  build-backend:

#  build-frontend:

#  test-frontend:

#  est-backend:

#  can-frontend:

#  scan-backend:

#  deploy-infrastructure:

#  configure-infrastructure:

#  run-migrations:

#  deploy-frontend:

#  deploy-backend:  

#  smoke-test:

#  cloudfront-update:

workflows:
  default:
    jobs:
      - build-backend
      - build-frontend

